// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user_info.proto

#include "user_info.pb.h"
#include "user_info.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* UserInfo_method_names[] = {
  "/UserInfo/SetUserInfo",
};

std::unique_ptr< UserInfo::Stub> UserInfo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserInfo::Stub> stub(new UserInfo::Stub(channel, options));
  return stub;
}

UserInfo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetUserInfo_(UserInfo_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UserInfo::Stub::SetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::SetUserInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SetUserInfoRequest, ::SetUserInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetUserInfo_, context, request, response);
}

void UserInfo::Stub::async::SetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest* request, ::SetUserInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SetUserInfoRequest, ::SetUserInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetUserInfo_, context, request, response, std::move(f));
}

void UserInfo::Stub::async::SetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest* request, ::SetUserInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetUserInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SetUserInfoResponse>* UserInfo::Stub::PrepareAsyncSetUserInfoRaw(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SetUserInfoResponse, ::SetUserInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetUserInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SetUserInfoResponse>* UserInfo::Stub::AsyncSetUserInfoRaw(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetUserInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

UserInfo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserInfo_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserInfo::Service, ::SetUserInfoRequest, ::SetUserInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserInfo::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SetUserInfoRequest* req,
             ::SetUserInfoResponse* resp) {
               return service->SetUserInfo(ctx, req, resp);
             }, this)));
}

UserInfo::Service::~Service() {
}

::grpc::Status UserInfo::Service::SetUserInfo(::grpc::ServerContext* context, const ::SetUserInfoRequest* request, ::SetUserInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


