// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user_info.proto
#ifndef GRPC_user_5finfo_2eproto__INCLUDED
#define GRPC_user_5finfo_2eproto__INCLUDED

#include "user_info.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class UserInfo final {
 public:
  static constexpr char const* service_full_name() {
    return "UserInfo";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::SetUserInfoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SetUserInfoResponse>> AsyncSetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SetUserInfoResponse>>(AsyncSetUserInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SetUserInfoResponse>> PrepareAsyncSetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SetUserInfoResponse>>(PrepareAsyncSetUserInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest* request, ::SetUserInfoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest* request, ::SetUserInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SetUserInfoResponse>* AsyncSetUserInfoRaw(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SetUserInfoResponse>* PrepareAsyncSetUserInfoRaw(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::SetUserInfoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SetUserInfoResponse>> AsyncSetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SetUserInfoResponse>>(AsyncSetUserInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SetUserInfoResponse>> PrepareAsyncSetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SetUserInfoResponse>>(PrepareAsyncSetUserInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest* request, ::SetUserInfoResponse* response, std::function<void(::grpc::Status)>) override;
      void SetUserInfo(::grpc::ClientContext* context, const ::SetUserInfoRequest* request, ::SetUserInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::SetUserInfoResponse>* AsyncSetUserInfoRaw(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SetUserInfoResponse>* PrepareAsyncSetUserInfoRaw(::grpc::ClientContext* context, const ::SetUserInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetUserInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SetUserInfo(::grpc::ServerContext* context, const ::SetUserInfoRequest* request, ::SetUserInfoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetUserInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetUserInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetUserInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetUserInfo(::grpc::ServerContext* /*context*/, const ::SetUserInfoRequest* /*request*/, ::SetUserInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetUserInfo(::grpc::ServerContext* context, ::SetUserInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::SetUserInfoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetUserInfo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SetUserInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetUserInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::SetUserInfoRequest, ::SetUserInfoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::SetUserInfoRequest* request, ::SetUserInfoResponse* response) { return this->SetUserInfo(context, request, response); }));}
    void SetMessageAllocatorFor_SetUserInfo(
        ::grpc::MessageAllocator< ::SetUserInfoRequest, ::SetUserInfoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::SetUserInfoRequest, ::SetUserInfoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetUserInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetUserInfo(::grpc::ServerContext* /*context*/, const ::SetUserInfoRequest* /*request*/, ::SetUserInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetUserInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::SetUserInfoRequest* /*request*/, ::SetUserInfoResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SetUserInfo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetUserInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetUserInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetUserInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetUserInfo(::grpc::ServerContext* /*context*/, const ::SetUserInfoRequest* /*request*/, ::SetUserInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetUserInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetUserInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetUserInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetUserInfo(::grpc::ServerContext* /*context*/, const ::SetUserInfoRequest* /*request*/, ::SetUserInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetUserInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetUserInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetUserInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetUserInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetUserInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetUserInfo(::grpc::ServerContext* /*context*/, const ::SetUserInfoRequest* /*request*/, ::SetUserInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetUserInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetUserInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetUserInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::SetUserInfoRequest, ::SetUserInfoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::SetUserInfoRequest, ::SetUserInfoResponse>* streamer) {
                       return this->StreamedSetUserInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetUserInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetUserInfo(::grpc::ServerContext* /*context*/, const ::SetUserInfoRequest* /*request*/, ::SetUserInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetUserInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::SetUserInfoRequest,::SetUserInfoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetUserInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetUserInfo<Service > StreamedService;
};


#endif  // GRPC_user_5finfo_2eproto__INCLUDED
